/**
 * Core market domain types.
 *
 * These are provider-agnostic. Every market data adapter normalises its
 * upstream payload into these shapes so the analysis engine never knows or
 * cares whether a candle came from Binance, Polygon or Twelve Data.
 */

/** Asset classes the platform can price. Drives provider routing. */
export const ASSET_CLASSES = ['crypto', 'forex', 'stock', 'index', 'commodity'] as const;
export type AssetClass = (typeof ASSET_CLASSES)[number];

/** Canonical timeframes. The string form is the wire/DB representation. */
export const TIMEFRAMES = ['1m', '5m', '15m', '30m', '1h', '4h', '1d', '1w'] as const;
export type Timeframe = (typeof TIMEFRAMES)[number];

/** Milliseconds per timeframe bucket — used for gap detection and alignment. */
export const TIMEFRAME_MS: Record<Timeframe, number> = {
  '1m': 60_000,
  '5m': 300_000,
  '15m': 900_000,
  '30m': 1_800_000,
  '1h': 3_600_000,
  '4h': 14_400_000,
  '1d': 86_400_000,
  '1w': 604_800_000,
};

/** Human labels for UI selectors. */
export const TIMEFRAME_LABELS: Record<Timeframe, string> = {
  '1m': '1m',
  '5m': '5m',
  '15m': '15m',
  '30m': '30m',
  '1h': '1H',
  '4h': '4H',
  '1d': '1D',
  '1w': '1W',
};

/**
 * Ordered ascending. Index position is used by the multi-timeframe engine to
 * find "the timeframe two steps up" without hardcoding pairs.
 */
export const TIMEFRAME_ORDER: readonly Timeframe[] = TIMEFRAMES;

/** A single OHLCV bar. `time` is the bar's OPEN time in epoch ms, UTC. */
export interface Candle {
  time: number;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  /** True when this bar is generated by the synthetic fallback feed. */
  synthetic?: boolean;
}

/** Latest price snapshot for a symbol. */
export interface Quote {
  symbol: string;
  price: number;
  /** Absolute change over the last 24h (or session, for equities). */
  change: number;
  /** Percentage change, e.g. -1.42 for -1.42%. */
  changePercent: number;
  high24h: number;
  low24h: number;
  /** Base-asset volume over the lookback window. */
  volume24h: number;
  /** Quote-currency volume when the provider supplies it. */
  quoteVolume24h?: number;
  timestamp: number;
  provider: string;
  synthetic?: boolean;
}

/** A tradable instrument tracked by the platform. */
export interface MarketSymbol {
  /** Internal canonical id, e.g. `BTCUSDT`, `XAUUSD`, `AAPL`, `SPX`. */
  symbol: string;
  /** Display name, e.g. "Bitcoin / TetherUS". */
  name: string;
  assetClass: AssetClass;
  /** Base asset — `BTC` for BTCUSDT, `AAPL` for AAPL. */
  base: string;
  /** Quote asset — `USDT`, `USD`. */
  quote: string;
  /** Decimal places for price display. */
  pricePrecision: number;
  /**
   * Smallest price increment for the instrument. Used by the risk engine when
   * converting stop distance into pips/ticks.
   */
  tickSize: number;
  /**
   * Contract/lot size. 100_000 for a standard FX lot, 1 for crypto & equities.
   */
  contractSize: number;
  /** TradingView symbol for the Advanced Chart widget, e.g. `BINANCE:BTCUSDT`. */
  tradingViewSymbol: string;
  /** Whether the platform should include it in automated signal scans. */
  scanEnabled: boolean;
  /** Sort weight for dashboard ordering (lower first). */
  displayOrder: number;
}

/** Crypto-only derivatives context that sharpens signal conviction. */
export interface DerivativesContext {
  symbol: string;
  /** Current perpetual funding rate as a decimal, e.g. 0.0001 = 0.01%. */
  fundingRate?: number;
  nextFundingTime?: number;
  /** Open interest in base units. */
  openInterest?: number;
  /** OI change over 24h as a percentage. */
  openInterestChangePercent?: number;
  /** Long/short account ratio where the venue exposes it. */
  longShortRatio?: number;
  timestamp: number;
}

/** alternative.me Fear & Greed reading. */
export interface FearGreedIndex {
  /** 0–100. */
  value: number;
  /** e.g. "Extreme Fear", "Greed". */
  classification: string;
  timestamp: number;
  previousValue?: number;
}

/** Order book depth snapshot — feeds liquidity-zone confirmation. */
export interface OrderBookLevel {
  price: number;
  quantity: number;
}

export interface OrderBook {
  symbol: string;
  bids: OrderBookLevel[];
  asks: OrderBookLevel[];
  timestamp: number;
}
